apiVersion: v1
kind: Pod 
metadata: 
  name: two-containers-same-volume-pod
spec: 
  volumes:
  - name: shared-data 
emptyDir: {} # This creates a temporary directory that is shared  
  between containers  
  containers: 
  - name: container-1 
image: nginx # Replace with your desired image
volumeMounts: 
- name: shared-data # This must match the volume name defined above   
  mountPath: /usr/share/nginx/html/shared # Path where the volume will
  be mounted in this container
  - name: container-2 
image: debian # Replace with your desired image   
command: ["/bin/sh", "-c"]
args: 
  - > 
while true; do
  echo "Container 2 writing to shared volume" >>  
  /data/shared/from_container2.txt;   
  ls -l /data/shared; 
  sleep 5;
done  
volumeMounts: 
- name: shared-data # This must match the volume name defined above   
  mountPath: /data/shared # Path where the volume will be mounted in  this container 
