apiVersion: batch/v1
kind: Job
metadata:
  name: my-gce-pvc-job
spec:
  template:
    spec:
      volumes:
        - name: gce-pvc-storage
          persistentVolumeClaim:
            claimName: my-gce-pvc-claim # <--- REPLACE WITH YOUR GCE PVC CLAIM NAME
      containers:
        - name: my-container
          image: busybox # You can use any image that has your desired commands
          command: ["sh", "-c"]
          args:
            - echo "Hello from the mounted GCE PVC!" > /mnt/gce_data/output.txt;
              ls -l /mnt/gce_data/;
              cat /mnt/gce_data/output.txt;
          volumeMounts:
            - name: gce-pvc-storage
              mountPath: /mnt/gce_data # <--- The path where the PVC will be mounted inside the container
      restartPolicy: Never

