apiVersion: v1
kind: Pod
metadata:
  name: two-containers-shared-volume-pod
spec:
  volumes:
    - name: shared-data-volume
      emptyDir: {} # This creates a temporary volume that exists for the life of the Pod
  containers:
    - name: container-writer
      image: busybox
      command: ["sh", "-c"]
      args:
        - echo "Hello from container-writer!" > /shared/message.txt;
          echo "Writing to shared volume completed.";
          sleep 10; # Keep the container running for a bit to observe
      volumeMounts:
        - name: shared-data-volume
          mountPath: /shared # Container 1 mounts the volume at /shared

    - name: container-reader
      image: busybox
      command: ["sh", "-c"]
      args:
        - sleep 5; # Give writer a moment to write
          echo "Reading from shared volume...";
          cat /shared/message.txt;
          echo "Reading from shared volume completed.";
      volumeMounts:
        - name: shared-data-volume
          mountPath: /shared # Container 2 also mounts the volume at /shared
