apiVersion: v1
kind: Pod
metadata:
  name: my-env-config-pod
spec:
  volumes:
    - name: app-config-volume
      configMap:
        name: my-app-config # <--- REPLACE WITH YOUR CONFIGMAP NAME
  containers:
    - name: my-app-container
      image: busybox # Or your application image
      imagePullPolicy: Always # <--- Image pull policy
      command: ["sh", "-c"]
      args:
        - echo "My custom greeting: $APP_GREETING";
          echo "Value from config file:";
          cat /config/app-settings.conf; # <--- Reading from mounted config volume
          sleep 3600; # Keep the container running
      env: # <--- Environment variables
        - name: APP_GREETING
          valueFrom:
            configMapKeyRef:
              name: my-app-config     # <--- REPLACE WITH YOUR CONFIGMAP NAME
              key: greeting_message   # <--- The key in the ConfigMap to use for APP_GREETING
        - name: ANOTHER_ENV_VAR
          valueFrom:
            configMapKeyRef:
              name: my-app-config     # <--- REPLACE WITH YOUR CONFIGMAP NAME
              key: another_value      # <--- Another key from the ConfigMap
      volumeMounts:
        - name: app-config-volume
          mountPath: /config # <--- Mount the ConfigMap volume at /config
          readOnly: true # <--- It's good practice to mount ConfigMaps as read-only
  restartPolicy: Never # <--- Restart policy for the Pod
