apiVersion: v1
kind: Pod 
metadata: 
  name: mypod-with-secrets
spec: 
  containers: 
  - name: mycontainer 
image: nginx # You can use any image  
env:  
  - name: MY_USERNAME 
valueFrom:
  secretKeyRef:   
name: mysecret # Name of the Secret   
key: username   # Key within the Secret   
  - name: MY_PASSWORD 
valueFrom:
  secretKeyRef:   
name: mysecret # Name of the Secret   
key: password   # Key within the Secret   
volumeMounts: 
- name: secret-volume 
  mountPath: "/etc/secret-volume" # Path where the secret will be 
  mounted 
  readOnly: true  
  volumes:
  - name: secret-volume   
secret:   
  secretName: mysecret # Name of the Secret to mount  
  items: # Optional: specify which keys to mount and their paths  
  - key: apikey   
path: my-api-key.txt # This will create a file named my-api-key.txt in /etc/secret-volume
