apiVersion: v1
kind: Pod
metadata:
  name: my-app-pod
  namespace: my-custom-namespace # <--- Specify the namespace here
spec:
  containers:
    - name: my-web-container
      image: nginx:latest # Example image, replace with your application image
      ports:
        - containerPort: 80
          name: http-web # <--- Named port
      resources:
        requests:
          memory: "64Mi" # Request 64 MiB of memory
          cpu: "250m"   # Request 0.25 CPU cores (250 milliCPU)
        limits:
          memory: "128Mi" # Limit to 128 MiB of memory
          cpu: "500m"    # Limit to 0.5 CPU cores (500 milliCPU)
      readinessProbe:
        httpGet:
          path: /healthz # <--- Specific path for the readiness check
          port: http-web # <--- Referencing the named port
          # host: example.com # Optional: If your pod runs on a specific host, specify it here
          # scheme: HTTPS # Optional: Use HTTPS if your app supports it
        initialDelaySeconds: 15 # <--- Initial delay before first probe (15 seconds)
        timeoutSeconds: 5       # <--- How long to wait for a response (5 seconds)
        periodSeconds: 10       # <--- How often to perform the probe (every 10 seconds)
        failureThreshold: 3     # <--- Number of consecutive failures before marking as Unready (3 failures)
