apiVersion: v1
kind: Pod 
metadata: 
  name: <your-pod-name>   
  namespace: <your-namespace> 
  labels: 
app: <your-app-label> 
spec: 
  containers: 
  - name: <your-container-name>   
image: <your-container-image> 
ports:
- name: <your-port-name> # e.g., http 
  containerPort: <your-container-port> # e.g., 80 
readinessProbe:   
  httpGet: # Assuming httpGet, common for path-based checks   
path: /<your-readiness-path> # e.g., /healthz 
port: <your-port-name-or-number> # Can be the name defined above  
  (e.g., http) or the port number 
  initialDelaySeconds: <integer_value> # e.g., 5  
  periodSeconds: <integer_value> # e.g., 10   
  timeoutSeconds: <integer_value> # e.g., 1   
  failureThreshold: <integer_value> # e.g., 3 
resources:
  requests:   
memory: "<memory_request_value>" # e.g., "64Mi"   
cpu: "<cpu_request_value>"# e.g., "250m"  
  limits: 
memory: "<memory_limit_value>" # e.g., "128Mi"
cpu: "<cpu_limit_value>"# e.g., "500m"

