apiVersion: v1
kind: Pod 
metadata: 
  name: mypod-with-secret-volume  
spec: 
  containers: 
  - name: myapp-container 
image: busybox # Using busybox for simplicity, replace with your image
command: ['sh', '-c', 'echo "My app is running and can read secrets   
  from /etc/mysecret/username:"; cat /etc/mysecret/username; echo "Sleeping   
  now..."; sleep 3600']   
volumeMounts: 
- name: secret-storage
  mountPath: "/etc/mysecret" # The path inside the container where the secret will be mounted  
  readOnly: true   # This makes the volume read-only  
  volumes:
  - name: secret-storage  
secret:   
  secretName: example-secret # This must match the name of your Secret
  # Optional: You can specify which keys from the secret to mount 
  # items:
  # - key: username   
  #   path: my-username # This will create a file 'my-username' in mountPath with the value of 'username' key  
