apiVersion: v1
kind: Pod 
metadata: 
  name: example-pod   
  labels: 
app.kubernetes.io/name: myapp 
app.kubernetes.io/instance: myapp-instance1   
spec: 
  containers: 
  - name: nginx-container 
image: nginx:latest # You can replace this with your desired image
ports:
- name: http # Optional: give a name to the port  
  containerPort: 80 # The port your application listens on inside the container   
  protocol: TCP # The protocol (TCP or UDP)   
# You can add more ports here if needed   
# - name: https   
#   containerPort: 443
#   protocol: TCP   
